### ISSUE TITLE
Buildings don't heal

### ISSUE THREAD

**Issue by jozzo402** [Remod-org/NoDecay#4]
Base parts under protection from no decay don't heal automatically if they're damaged, eg. by patrol heli.

**Comment by RFC1920** [comment]
I think this has always been an issue for damage plugins.  Definitely worth looking into.

**Comment by RFC1920** [comment]
This should be addressed with some new config, etc., in 1.0.89.

**Comment by RFC1920** [comment]
See new configs:
"healBuildings"
"healEntities"
"healPercentage"
